name: test

on:
  push:
    branches:
      - develop
      - main
  schedule:
    - cron: "0 0 * * 0" # weekly
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Request manual activation file
        id: alfFile
        uses: game-ci/unity-request-activation-file@main

      - name: Activate license
        id: activate
        run: |
          node dist/index.js --username "${{ secrets.UNITY_EMAIL }}" --password "${{ secrets.UNITY_PASSWORD }}" --key "${{ secrets.UNITY_AUTHENTICATOR_KEY }}" -d "${{ steps.alfFile.outputs.filePath }}"

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: error.html
          path: error.html
